# R Compatibility Test for Methrix CLI

This script verifies that H5 files generated by methrix-cli are compatible with the R methrix package.

## Prerequisites

```r
# Install required packages
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install(c("methrix", "HDF5Array", "SummarizedExperiment"))
```

## Test Script

```r
library(methrix)
library(HDF5Array)
library(testthat)

# Path to H5 file generated by methrix-cli
h5_path <- "results/methrix_data.h5"

test_that("H5 file can be loaded", {
  expect_true(file.exists(h5_path))

  # Load the H5 file
  m <- load_HDF5_methrix(h5_path)

  # Verify it's a methrix object
  expect_s3_class(m, "methrix")
})

test_that("Basic methrix operations work", {
  m <- load_HDF5_methrix(h5_path)

  # Check class properties
  expect_true(is_h5(m))

  # Get dimensions
  n_cpgs <- nrow(m)
  n_samples <- ncol(m)
  expect_gt(n_cpgs, 0)
  expect_gt(n_samples, 0)
})

test_that("Matrix extraction works", {
  m <- load_HDF5_methrix(h5_path)

  # Extract methylation matrix
  beta <- get_matrix(m, type = "M")
  expect_true(is.matrix(beta))
  expect_true(all(beta >= 0 & beta <= 1, na.rm = TRUE))

  # Extract coverage matrix
  cov <- get_matrix(m, type = "C")
  expect_true(is.matrix(cov))
  expect_true(all(cov >= 0, na.rm = TRUE))
})

test_that("Statistics calculation works", {
  m <- load_HDF5_methrix(h5_path)

  stats <- get_stats(m)
  expect_true(nrow(stats) > 0)
  expect_true("mean_cov" %in% names(stats))
  expect_true("mean_meth" %in% names(stats))
})

test_that("QC plots can be generated", {
  m <- load_HDF5_methrix(h5_path)

  # These should not throw errors
  expect_silent(plot_coverage(m))
  expect_silent(plot_density(m))
  expect_silent(plot_violin(m))
})

# Run all tests
test_file("tests/integration/test_r_compatibility.R")
```

## Expected Output

If everything is working correctly, you should see:

```
✔ | OK F W  S | Context
✔ |  8       8 | tests/integration/test_r_compatibility.R
```

## Troubleshooting

### Loading errors

If you get errors loading the H5 file:

1. **Check HDF5 version compatibility**:
```r
ruler::hdf5_version()
```

2. **Verify file structure**:
```r
h5ls(h5_path)
```

3. **Check dataset dimensions**:
```r
library(hdf5r)
h5file <- H5Fopen(h5_path)
h5dim <- H5Sget_simple_extent_dims(h5file$open("assays/beta")$get_space())
print(h5dim)
H5Fclose(h5file)
```

### Common issues

- **"Dataset not found"**: Check that the H5 file has the expected structure (assays/beta, assays/cov, etc.)
- **"Dimension mismatch"**: Verify that beta and cov matrices have the same dimensions
- **"Type conversion error"**: Ensure beta values are stored as f32 and cov as u16
